version: '3.5'
services:
 users_db:
  image: mongo:latest
  container_name: "users_db"
  environment:
   - MONGO_DATA_DIR=/usr/data/db
   - MONGO_LOG_DIR=/dev/null
  volumes:
   - ./data/db:/usr/data/db
  ports:
   - 27017:27017
  command: mongod --logpath=/dev/null # --quiet
 user_notes_db:
  image: mongo:latest
  container_name: "user_notes_db"
  environment:
   - MONGO_DATA_DIR=/usr/data/db
   - MONGO_LOG_DIR=/dev/null
  volumes:
   - ./data/db:/usr/data/db
  ports:
   - 27018:27017
  command: mongod --logpath=/dev/null # --quiet
 users:
  container_name: "users"
  build:
   context: ./services/users
   dockerfile: Dockerfile
  ports:
   - "4001:4001"
  environment:
   - ENV=development
   - DB=mongodb://users_db:27017/users
 user_notes:
  container_name: "user_notes"
  build:
    context: ./services/user_notes
    dockerfile: Dockerfile
  ports:
   - "4002:4002"
  environment:
   - ENV=development
   - DB=mongodb://user_notes_db:27018/user_notes
 web:
  container_name: "web"
  build:
   context: ./services/web
   dockerfile: Dockerfile
  ports:
   - "4000:4000"
  environment:
   - ENV=development
